# Generated by Django 2.1.5 on 2019-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='client', max_length=100),
            preserve_default=False,
        ),
    ]
