# Generated by Django 2.1.5 on 2019-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='debit',
            field=models.IntegerField(default=0, verbose_name='Debit/Credit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier')], max_length=100),
        ),
    ]
