# Generated by Django 2.1.5 on 2019-01-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20190111_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='previous_credit',
            field=models.IntegerField(default=0),
        ),
    ]
