# Generated by Django 2.1.5 on 2019-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20190113_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_stock',
            field=models.IntegerField(default=0),
        ),
    ]
