# Generated by Django 2.1.5 on 2019-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_inventoryitem_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Sale', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_kg_sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
