# Generated by Django 2.1.5 on 2019-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20190118_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
