# Generated by Django 2.1.5 on 2019-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='price_per_kg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
